In [1]:
import numpy as np
import pandas as pd

In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [7]:
import statsmodels.api as sm

In [10]:
affairs_df = sm.datasets.fair.load_pandas().data

In [11]:
affairs_df

rate_marriage   age  yrs_married  children  religious  educ  occupation  \
0               3.0  32.0          9.0       3.0        3.0  17.0         2.0   
1               3.0  27.0         13.0       3.0        1.0  14.0         3.0   
2               4.0  22.0          2.5       0.0        1.0  16.0         3.0   
3               4.0  37.0         16.5       4.0        3.0  16.0         5.0   
4               5.0  27.0          9.0       1.0        1.0  14.0         3.0   
...             ...   ...          ...       ...        ...   ...         ...   
6361            5.0  32.0         13.0       2.0        3.0  17.0         4.0   
6362            4.0  32.0         13.0       1.0        1.0  16.0         5.0   
6363            5.0  22.0          2.5       0.0        2.0  14.0         3.0   
6364            5.0  32.0          6.0       1.0        3.0  14.0         3.0   
6365            4.0  22.0          2.5       0.0        2.0  16.0         2.0   

      occupation_husb   affairs  
0                 5.0  0.111111  
1                 4.0  3.230769  
2                 5.0  1.400000  
3                 5.0  0.727273  
4                 4.0  4.666666  
...               ...       ...  
6361              3.0  0.000000  
6362              5.0  0.000000  
6363              1.0  0.000000  
6364              4.0  0.000000  
6365              4.0  0.000000  

[6366 rows x 9 columns]

In [12]:
affairs_df.keys()

Index(['rate_marriage', 'age', 'yrs_married', 'children', 'religious', 'educ',
       'occupation', 'occupation_husb', 'affairs'],
      dtype='object')

In [18]:
affairs_df["affair"] = (affairs_df.affairs > 0).astype(int)

In [19]:
affairs_df

rate_marriage   age  yrs_married  children  religious  educ  occupation  \
0               3.0  32.0          9.0       3.0        3.0  17.0         2.0   
1               3.0  27.0         13.0       3.0        1.0  14.0         3.0   
2               4.0  22.0          2.5       0.0        1.0  16.0         3.0   
3               4.0  37.0         16.5       4.0        3.0  16.0         5.0   
4               5.0  27.0          9.0       1.0        1.0  14.0         3.0   
...             ...   ...          ...       ...        ...   ...         ...   
6361            5.0  32.0         13.0       2.0        3.0  17.0         4.0   
6362            4.0  32.0         13.0       1.0        1.0  16.0         5.0   
6363            5.0  22.0          2.5       0.0        2.0  14.0         3.0   
6364            5.0  32.0          6.0       1.0        3.0  14.0         3.0   
6365            4.0  22.0          2.5       0.0        2.0  16.0         2.0   

      occupation_husb   affairs  affair  
0                 5.0  0.111111       1  
1                 4.0  3.230769       1  
2                 5.0  1.400000       1  
3                 5.0  0.727273       1  
4                 4.0  4.666666       1  
...               ...       ...     ...  
6361              3.0  0.000000       0  
6362              5.0  0.000000       0  
6363              1.0  0.000000       0  
6364              4.0  0.000000       0  
6365              4.0  0.000000       0  

[6366 rows x 10 columns]

In [20]:
affairs_df['affairs'].value_counts()

0.000000     4313
1.400000      118
0.583333       86
0.400000       72
1.333333       72
             ... 
3.878787        1
7.111111        1
39.199982       1
4.923077        1
57.599991       1
Name: affairs, Length: 77, dtype: int64

In [25]:
affairs_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6366 entries, 0 to 6365
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   rate_marriage    6366 non-null   float64
 1   age              6366 non-null   float64
 2   yrs_married      6366 non-null   float64
 3   children         6366 non-null   float64
 4   religious        6366 non-null   float64
 5   educ             6366 non-null   float64
 6   occupation       6366 non-null   float64
 7   occupation_husb  6366 non-null   float64
 8   affairs          6366 non-null   float64
 9   affair           6366 non-null   int32  
dtypes: float64(9), int32(1)
memory usage: 472.6 KB


In [28]:
(affairs_df.affairs > 0)

0        True
1        True
2        True
3        True
4        True
        ...  
6361    False
6362    False
6363    False
6364    False
6365    False
Name: affairs, Length: 6366, dtype: bool

In [27]:
(affairs_df.affairs > 0).astype(int)

0       1
1       1
2       1
3       1
4       1
       ..
6361    0
6362    0
6363    0
6364    0
6365    0
Name: affairs, Length: 6366, dtype: int32

In [36]:
affairs_df['occupation'].unique()

array([2., 3., 5., 4., 1., 6.])

In [30]:
import patsy as pt

In [33]:
y, x = pt.dmatrices('affair ~ rate_marriage + age + yrs_married + children +  religious + educ + C(occupation) + C(occupation_husb)',data=affairs_df, return_type='dataframe')

In [34]:
x

Intercept  C(occupation)[T.2.0]  C(occupation)[T.3.0]  \
0           1.0                   1.0                   0.0   
1           1.0                   0.0                   1.0   
2           1.0                   0.0                   1.0   
3           1.0                   0.0                   0.0   
4           1.0                   0.0                   1.0   
...         ...                   ...                   ...   
6361        1.0                   0.0                   0.0   
6362        1.0                   0.0                   0.0   
6363        1.0                   0.0                   1.0   
6364        1.0                   0.0                   1.0   
6365        1.0                   1.0                   0.0   

      C(occupation)[T.4.0]  C(occupation)[T.5.0]  C(occupation)[T.6.0]  \
0                      0.0                   0.0                   0.0   
1                      0.0                   0.0                   0.0   
2                      0.0                   0.0                   0.0   
3                      0.0                   1.0                   0.0   
4                      0.0                   0.0                   0.0   
...                    ...                   ...                   ...   
6361                   1.0                   0.0                   0.0   
6362                   0.0                   1.0                   0.0   
6363                   0.0                   0.0                   0.0   
6364                   0.0                   0.0                   0.0   
6365                   0.0                   0.0                   0.0   

      C(occupation_husb)[T.2.0]  C(occupation_husb)[T.3.0]  \
0                           0.0                        0.0   
1                           0.0                        0.0   
2                           0.0                        0.0   
3                           0.0                        0.0   
4                           0.0                        0.0   
...                         ...                        ...   
6361                        0.0                        1.0   
6362                        0.0                        0.0   
6363                        0.0                        0.0   
6364                        0.0                        0.0   
6365                        0.0                        0.0   

      C(occupation_husb)[T.4.0]  C(occupation_husb)[T.5.0]  \
0                           0.0                        1.0   
1                           1.0                        0.0   
2                           0.0                        1.0   
3                           0.0                        1.0   
4                           1.0                        0.0   
...                         ...                        ...   
6361                        0.0                        0.0   
6362                        0.0                        1.0   
6363                        0.0                        0.0   
6364                        1.0                        0.0   
6365                        1.0                        0.0   

      C(occupation_husb)[T.6.0]  rate_marriage   age  yrs_married  children  \
0                           0.0            3.0  32.0          9.0       3.0   
1                           0.0            3.0  27.0         13.0       3.0   
2                           0.0            4.0  22.0          2.5       0.0   
3                           0.0            4.0  37.0         16.5       4.0   
4                           0.0            5.0  27.0          9.0       1.0   
...                         ...            ...   ...          ...       ...   
6361                        0.0            5.0  32.0         13.0       2.0   
6362                        0.0            4.0  32.0         13.0       1.0   
6363                        0.0            5.0  22.0          2.5       0.0   
6364                        0.0            5.0  32.0          6.0       1.0   
6

In [37]:
x = x.rename(columns =
{
'C(occupation)[T.2.0]':'occ_2',
'C(occupation)[T.3.0]':'occ_3',
'C(occupation)[T.4.0]':'occ_4',
'C(occupation)[T.5.0]':'occ_5',
'C(occupation)[T.6.0]':'occ_6',
'C(occupation_husb)[T.2.0]':'occ_husb_2',
'C(occupation_husb)[T.3.0]':'occ_husb_3',
'C(occupation_husb)[T.4.0]':'occ_husb_4',
'C(occupation_husb)[T.5.0]':'occ_husb_5',
'C(occupation_husb)[T.6.0]':'occ_husb_6'
})

In [38]:
x

Intercept  occ_2  occ_3  occ_4  occ_5  occ_6  occ_husb_2  occ_husb_3  \
0           1.0    1.0    0.0    0.0    0.0    0.0         0.0         0.0   
1           1.0    0.0    1.0    0.0    0.0    0.0         0.0         0.0   
2           1.0    0.0    1.0    0.0    0.0    0.0         0.0         0.0   
3           1.0    0.0    0.0    0.0    1.0    0.0         0.0         0.0   
4           1.0    0.0    1.0    0.0    0.0    0.0         0.0         0.0   
...         ...    ...    ...    ...    ...    ...         ...         ...   
6361        1.0    0.0    0.0    1.0    0.0    0.0         0.0         1.0   
6362        1.0    0.0    0.0    0.0    1.0    0.0         0.0         0.0   
6363        1.0    0.0    1.0    0.0    0.0    0.0         0.0         0.0   
6364        1.0    0.0    1.0    0.0    0.0    0.0         0.0         0.0   
6365        1.0    1.0    0.0    0.0    0.0    0.0         0.0         0.0   

      occ_husb_4  occ_husb_5  occ_husb_6  rate_marriage   age  yrs_married  \
0            0.0         1.0         0.0            3.0  32.0          9.0   
1            1.0         0.0         0.0            3.0  27.0         13.0   
2            0.0         1.0         0.0            4.0  22.0          2.5   
3            0.0         1.0         0.0            4.0  37.0         16.5   
4            1.0         0.0         0.0            5.0  27.0          9.0   
...          ...         ...         ...            ...   ...          ...   
6361         0.0         0.0         0.0            5.0  32.0         13.0   
6362         0.0         1.0         0.0            4.0  32.0         13.0   
6363         0.0         0.0         0.0            5.0  22.0          2.5   
6364         1.0         0.0         0.0            5.0  32.0          6.0   
6365         1.0         0.0         0.0            4.0  22.0          2.5   

      children  religious  educ  
0          3.0        3.0  17.0  
1          3.0        1.0  14.0  
2          0.0        1.0  16.0  
3          4.0        3.0  16.0  
4          1.0        1.0  14.0  
...        ...        ...   ...  
6361       2.0        3.0  17.0  
6362       1.0        1.0  16.0  
6363       0.0        2.0  14.0  
6364       1.0        3.0  14.0  
6365       0.0        2.0  16.0  

[6366 rows x 17 columns]

In [39]:
y

affair
0        1.0
1        1.0
2        1.0
3        1.0
4        1.0
...      ...
6361     0.0
6362     0.0
6363     0.0
6364     0.0
6365     0.0

[6366 rows x 1 columns]

In [40]:
y = np.ravel(y)

In [41]:
y

array([1., 1., 1., ..., 0., 0., 0.])

In [44]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.30,random_state=42)

In [45]:
model = LogisticRegression()

In [46]:
model.fit(x_train,y_train)

C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [52]:
y_pred=model.predict(x_test)

In [54]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [53]:
accuracy_score(y_test,y_pred)

0.7277486910994765

In [55]:
confusion_matrix(y_test,y_pred)

array([[1147,  128],
       [ 392,  243]], dtype=int64)